name: bandersnatch_docker_upload

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: pypa/bandersnatch
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@master
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: pypa/bandersnatch
